In [1]:
import numpy as np

# Understanding NumPy Basics and NumPy Arrays

In [2]:
# Integer Array
np.array([1,4,5,2,3])

array([1, 4, 5, 2, 3])

In [3]:
np.array([3.14,2,6,8])

array([3.14, 2.  , 6.  , 8.  ])

In [4]:
np.array([2.13,1,4,5], dtype='int16')

array([2, 1, 4, 5], dtype=int16)

In [5]:
np.array([2.13,1,4,5], dtype='float32')

array([2.13, 1.  , 4.  , 5.  ], dtype=float32)

In [6]:
# Nested lists result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])
# The inner lists are treated as rows of the resulting two-dimensional array.

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [7]:
# Create a length-10 array filled with zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Remember that in np.zeros and np.ones the default data type is float

In [11]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [12]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
np.linspace(1,10,10, dtype='int16')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int16)

In [15]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.31425274, 0.69297887, 0.72668465],
       [0.00274593, 0.14494575, 0.92800902],
       [0.58376571, 0.33751672, 0.17918185]])

In [16]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-2.21156373,  0.49329883, -1.29789478],
       [-1.08823607, -2.35203822, -2.10035499],
       [-0.37402344, -1.13024213,  0.79410138]])

In [17]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[1, 0, 8],
       [2, 9, 4],
       [1, 1, 1]])

In [18]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([1., 1., 1.])