In [1]:
import numpy as np

# NumPy Array Attributes

In [2]:
np.random.seed(0) # seed for reproducibility

x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [5]:
x1.ndim # Returns the dimension of the NumPy array

1

In [7]:
x3.ndim

3

In [8]:
x3.shape # Returns size of each dimension of array

(3, 4, 5)

In [9]:
x2.shape

(3, 4)

In [12]:
x1.shape

(6,)

In [13]:
x2.size # Returns total size of array

12

In [14]:
x3.dtype # Returns the data type of the array

dtype('int64')

In [15]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

# itemsize lists the size (in bytes) of each array element
# nbytes lists the total size (in bytes) of the array

itemsize: 8 bytes
nbytes: 480 bytes


In [18]:
# nbytes is equal to itemsize times size 
x2.nbytes 

96

In [19]:
x2.itemsize * x2.size

96

# Array Indexing: Accessing Single Elements

In [20]:
x1

array([5, 0, 3, 3, 7, 9])

In [21]:
x1[4]

7

In [22]:
x1[0]

5

In [23]:
x1[-2]

7

In [24]:
x2[0][1]

5

In [25]:
x2[0,1]

5

In [26]:
x1[0] = 10

In [27]:
x1

array([10,  0,  3,  3,  7,  9])

In [28]:
# Unlike Python lists, NumPy arrays have a fixed type
x1[0] = 3.14159 # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

# Array Slicing: Accessing Subarrays

The NumPy slicing syntax follows that of the standard Python list; to access a slice of
an array x, use this:

x [start: stop: step]

In [30]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
x[2:6]

array([2, 3, 4, 5])

In [32]:
x[1:8:3]

array([1, 4, 7])

In [33]:
x[:4]

array([0, 1, 2, 3])

In [34]:
x[1::2]

array([1, 3, 5, 7, 9])

In [35]:
x[::-2]

array([9, 7, 5, 3, 1])

In [36]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [37]:
# Multidimensional slices work in the same way, with multiple slices separated by commmas
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [38]:
x2[:3,:2] # Three rows and Two Columns

array([[3, 5],
       [7, 6],
       [1, 6]])

In [39]:
# subarray dimensions can even be reversed together
x2[::-1,::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

# Applying Array Slicing and Indexing

In [41]:
# Accessing single rows and columns can be done by array slicing and array indexing
x2[:,0]

array([3, 7, 1])

In [42]:
x2[0,:]

array([3, 5, 2, 4])

In [43]:
x2[0]

array([3, 5, 2, 4])

In [45]:
x2[0][0] = 12

### One important—and extremely useful—thing to know about array slices is that they return views rather than copies of the array data

In [46]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [48]:
x2_sub = x2[:2,:2]
x2_sub

array([[12,  5],
       [ 7,  6]])

In [49]:
x2_sub[0,0] = 99
x2_sub

array([[99,  5],
       [ 7,  6]])

In [50]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [51]:
# To create copies of an array we can use the copy method
x2_copy = x2.copy()

In [53]:
x2_copy

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

# Reshaping of Arrays

In [58]:
x = np.array(range(3))
x

array([0, 1, 2])

In [60]:
x.reshape(3,1)

array([[0],
       [1],
       [2]])

In [61]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Array Concatenation and Splitting 

In [62]:
x1

array([3, 0, 3, 3, 7, 9])

In [63]:
x = np.array([12,54,31])

In [65]:
np.concatenate([x,x1])

array([12, 54, 31,  3,  0,  3,  3,  7,  9])

In [66]:
x2_copy

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [67]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [68]:
np.concatenate([x2_copy,x2])

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7],
       [99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [73]:
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([7,8,9])
c = np.array([[7],
            [8]])

In [71]:
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
np.hstack([a,c])

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

In [75]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [76]:
grid = np.arange(16).reshape((4, 4))

upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
