In [1]:
import numpy as np

# Comparison Operators as ufuncs

In [2]:
x = np.array([1,2,3,4,5])
x < 3

array([ True,  True, False, False, False])

In [3]:
x > 3

array([False, False, False,  True,  True])

In [4]:
x <= 3

array([ True,  True,  True, False, False])

In [5]:
# We can do element by element comparison also
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

In [6]:
# We have numpy ufuncs for these operations
np.less(3,x) # Similar ot np.greater(x,3)

array([False, False, False,  True,  True])

In [9]:
np.less(x,3)

array([ True,  True, False, False, False])

In [10]:
np.greater_equal(x,2)

array([False,  True,  True,  True,  True])

In [18]:
#Comparing the time taken by the two methods

a = np.random.randint(0,10000,(1,1000))

In [19]:
a

array([[3688, 5944, 8858, 6781, 2198, 8820, 5064, 2655, 7350, 6184, 9882,
        5901, 2373,  370, 2412, 6147, 9334, 5763,  628, 8992, 4723, 2459,
        9704,  113, 2085, 9430, 6948, 2437, 8351, 6043, 8946, 6239,  147,
        8849, 2418, 7079, 3137, 7448, 6396, 6611, 7013, 9525, 4763, 7067,
        4515, 2996, 7835,  839, 9538, 3768, 7089, 8312, 1891, 5083, 1756,
        3796, 1413, 7697,  278,  179, 3381, 5015, 2007, 3844, 6279, 4978,
        5322,  472, 5403, 6369, 5401, 2768, 4332, 6772, 5175, 3770, 9335,
        5896,  442, 9899, 4280, 5788, 6586, 2470, 8345, 4222, 4044, 3652,
        1851, 4302, 8970, 9054, 1978, 5513, 7654, 6325, 4274, 4394, 8834,
        8795, 9326, 2477,    5, 8709, 3585,  737, 3826, 2662, 2777,  453,
        8074, 9371, 1943, 2648,  326, 8116, 4944, 9280, 7398, 2047, 8385,
        7490, 4251, 2969, 8220, 4809,  950, 9880, 8318, 8282, 9486, 5493,
         278, 2257, 8131, 6450, 1578, 5867, 6413, 1501, 3069, 4821, 8823,
        7432, 4571, 9754, 8876, 8300, 

In [20]:
%timeit a>3456

The slowest run took 46.01 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 1.43 µs per loop


In [21]:
%timeit np.greater(a,3456)

The slowest run took 37.78 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 1.41 µs per loop


In [22]:
rng = np.random.RandomState(0)

In [25]:
x = rng.randint(10,size=(3,4))

In [26]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [27]:
x<6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

# Working with Boolean Arrays

In [28]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [31]:
np.count_nonzero(x<6)
# To count the number of True entries in a Boolean array, 
# np.count_nonzero is useful

8

In [32]:
# Another way to get at this
# information is to use np.sum
# in this case, False is interpreted as 0 ,
# and True is interpreted as 1

np.sum(x<6)

8

In [33]:
np.sum(x)

54

In [34]:
np.sum(x<6,0)

array([2, 2, 2, 2])

In [36]:
np.sum(x<6,1)

array([4, 2, 2])

In [37]:
# Comparing times 
%timeit np.sum(a<3456)

The slowest run took 224.34 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 5.35 µs per loop


In [38]:
%timeit np.count_nonzero(a<3456)

The slowest run took 36.47 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 1.99 µs per loop


In [39]:
# Even though count_nonzero is faster the advantage of np.sum() is that
# we can do the operations along rows or columns as well

In [41]:
# are there any values greater than 8?
np.any(x > 8)

True

In [42]:
# are there any values less than zero?
np.any(x < 0)

False

In [43]:
# are all values less than 10?
np.all(x < 10)

True

In [44]:
# are all values equal to 6?
np.all(x == 6)

False

In [45]:
# np.all() and np.any() can be used along particular axes as well
np.all(x<8,1)

array([ True, False,  True])

In [46]:
np.all(x<8,0)

array([ True, False,  True,  True])

### Boolean Operators

In [56]:
np.sum((x>5) & (x<10))

IndexError: index 4 is out of bounds for axis 0 with size 3

In [50]:
np.bitwise_and((x>5),(x<10))

array([[False, False, False, False],
       [ True,  True, False, False],
       [False, False,  True,  True]])

 &     :   np.bitwise_and

|     :   np.bitwise_or

^     :   np.bitwise_xor

~     :   np.bitwise_not

# Boolean Arrays as Masks

In [52]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [53]:
x<5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [55]:
# Now to select these values from the array,
# we can simply index on this Boolean array;
# this is known as a masking operation

x[x<5]

array([0, 3, 3, 3, 2, 4])

In [59]:
np.random.rand??

In [70]:
(np.arange(365)-172 < 90) & (np.arange(365) - 172 > 0)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [71]:
bool(9)

True

In [72]:
bool(0)

False

In [74]:
# Difference between (and) and (&) ; (or) and (|)
# and and or gauge the truth or falsehood of entire object, 
# while & and | refer to bits within each object
A = np.array([1, 0, 1, 0, 1, 0], dtype=bool)
B = np.array([1, 1, 1, 0, 1, 1], dtype=bool)

In [75]:
A | B

array([ True,  True,  True, False,  True,  True])

In [76]:
A or B

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()