In [2]:
import numpy as np

In [3]:
# Never to be used sorting algorithm
def bogosort(x):
    while(np.any(x[:-1] > x[1:])):
        np.random.shuffle(x)
    return x

In [46]:
x = np.random.randint(1000,size = 100)
x

array([662, 872, 739, 444, 200, 693, 261, 328, 483, 361,  45, 667,  48,
       910, 546, 630, 380,  67, 597, 109, 127,  69, 177, 764, 544, 595,
       339, 349, 919, 461, 578, 344, 545, 590,  26, 310, 977, 515, 434,
       561,  12, 911, 742, 606, 866,  65, 491, 341, 902, 162,   9,  45,
       145, 241, 287, 570,  97, 225,  39, 775, 630, 132, 201,  14, 145,
        20, 147, 366, 526, 378, 298, 741, 800, 109, 177, 321, 183, 652,
       684, 483, 837, 164, 649, 592, 769, 495, 578, 459,  45, 362, 198,
       770, 455, 229, 643, 467, 158,  32, 100, 293])

In [33]:
# Don't run this statement with timeit...run with time
# %time bogosort(x)

In [34]:
%time np.sort(x)

CPU times: user 62 µs, sys: 0 ns, total: 62 µs
Wall time: 66 µs


array([  3,   8,  26,  52,  55,  63,  63,  98, 101, 105, 115, 125, 126,
       135, 135, 138, 144, 158, 163, 171, 175, 178, 183, 189, 215, 217,
       218, 220, 240, 240, 271, 287, 291, 293, 335, 340, 343, 354, 377,
       377, 382, 384, 391, 399, 403, 407, 408, 411, 412, 420, 420, 430,
       439, 439, 459, 467, 508, 514, 516, 533, 535, 548, 568, 574, 600,
       604, 608, 609, 654, 668, 669, 694, 710, 717, 722, 726, 729, 740,
       783, 793, 796, 812, 817, 821, 828, 846, 848, 850, 879, 885, 886,
       886, 895, 919, 956, 964, 972, 984, 993, 998])

In [35]:
%time np.sort(x)

CPU times: user 51 µs, sys: 0 ns, total: 51 µs
Wall time: 55.3 µs


array([  3,   8,  26,  52,  55,  63,  63,  98, 101, 105, 115, 125, 126,
       135, 135, 138, 144, 158, 163, 171, 175, 178, 183, 189, 215, 217,
       218, 220, 240, 240, 271, 287, 291, 293, 335, 340, 343, 354, 377,
       377, 382, 384, 391, 399, 403, 407, 408, 411, 412, 420, 420, 430,
       439, 439, 459, 467, 508, 514, 516, 533, 535, 548, 568, 574, 600,
       604, 608, 609, 654, 668, 669, 694, 710, 717, 722, 726, 729, 740,
       783, 793, 796, 812, 817, 821, 828, 846, 848, 850, 879, 885, 886,
       886, 895, 919, 956, 964, 972, 984, 993, 998])

In [40]:
%time  x.sort()

CPU times: user 34 µs, sys: 0 ns, total: 34 µs
Wall time: 39.1 µs


In [47]:
i = np.argsort(x) 
# A related function is argsort , which instead 
# returns the indices of the sorted elements

In [49]:
i

array([50, 40, 63, 65, 34, 97, 58, 88, 51, 10, 12, 45, 17, 21, 56, 98, 19,
       73, 20, 61, 52, 64, 66, 96, 49, 81, 22, 74, 76, 90,  4, 62, 57, 93,
       53,  6, 54, 99, 70, 35, 75,  7, 26, 47, 31, 27,  9, 89, 67, 69, 16,
       38,  3, 92, 87, 29, 95, 79,  8, 46, 85, 37, 68, 24, 32, 14, 39, 55,
       86, 30, 33, 83, 25, 18, 43, 60, 15, 94, 82, 77,  0, 11, 78,  5,  2,
       71, 42, 23, 84, 91, 59, 72, 80, 44,  1, 48, 13, 41, 28, 36])

In [50]:
x[i]

array([  9,  12,  14,  20,  26,  32,  39,  45,  45,  45,  48,  65,  67,
        69,  97, 100, 109, 109, 127, 132, 145, 145, 147, 158, 162, 164,
       177, 177, 183, 198, 200, 201, 225, 229, 241, 261, 287, 293, 298,
       310, 321, 328, 339, 341, 344, 349, 361, 362, 366, 378, 380, 434,
       444, 455, 459, 461, 467, 483, 483, 491, 495, 515, 526, 544, 545,
       546, 561, 570, 578, 578, 590, 592, 595, 597, 606, 630, 630, 643,
       649, 652, 662, 667, 684, 693, 739, 741, 742, 764, 769, 770, 775,
       800, 837, 866, 872, 902, 910, 911, 919, 977])

## Sorting along rows or columns

In [51]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [52]:
np.sort(X,0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [54]:
np.sort(X,1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

# Partial Sorting

In [55]:
x = np.array([7, 2, 3, 1, 6, 5, 4])

In [56]:
np.partition(x, 3)
# To find the first 3 smallest values in the array

array([2, 1, 3, 4, 6, 5, 7])

In [57]:
np.partition(x, 4)
# To find the first 4 smallest values in the array

array([2, 1, 3, 4, 5, 6, 7])

In [58]:
# Similarly to sorting, we can
# partition along an arbitrary axis 
# of a multidimensional array
X

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [59]:
np.partition(X, 2, axis=1)

array([[3, 4, 6, 7, 6, 9],
       [2, 3, 4, 7, 6, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 9, 5]])

In [60]:
# We can also use np.argpartition like np.argsort
np.argpartition(x,3)

array([1, 3, 2, 6, 4, 5, 0])

5